--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    id bigint NOT NULL,
    writer_name character varying(255),
    parent_id bigint,
    updated_at timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL
);


--
-- Name: comments_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.comments_comment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: comments_comment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.comments_comment_id_seq OWNED BY public.comments.comment_id;


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_posts (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    grade character varying(20) NOT NULL,
    interview_type character varying(20) NOT NULL,
    level character varying(255),
    like_count integer NOT NULL,
    score integer NOT NULL,
    scrap_count integer NOT NULL,
    summary character varying(1000),
    title character varying(50),
    type character varying(255),
    view_count integer NOT NULL,
    writer_name character varying(255),
    post_id bigint NOT NULL,
    content text NOT NULL,
    user_id bigint NOT NULL,
    tech_tag character varying(50),
    interview_feedback text,
    interview_result_id bigint,
    deleted boolean DEFAULT false NOT NULL,
    CONSTRAINT community_posts_grade_check CHECK (((grade)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying, 'E'::character varying, 'F'::character varying])::text[]))),
    CONSTRAINT community_posts_interview_type_check CHECK (((interview_type)::text = ANY ((ARRAY['PRACTICE'::character varying, 'REAL'::character varying])::text[])))
);


--
-- Name: community_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.community_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_posts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.community_posts ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_posts_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communityposts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.communityposts (
    post_id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(50) NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone NOT NULL
);


--
-- Name: communityposts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.communityposts_post_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: communityposts_post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.communityposts_post_id_seq OWNED BY public.communityposts.post_id;


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: interview_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_answers (
    answer_id bigint NOT NULL,
    answer_text text NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    question_id bigint NOT NULL
);


--
-- Name: interview_answers_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_answers ALTER COLUMN answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_answers_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_questions (
    question_id bigint NOT NULL,
    category character varying(50) NOT NULL,
    text text NOT NULL,
    interview_id bigint NOT NULL
);


--
-- Name: interview_questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_results (
    result_id bigint NOT NULL,
    feedback text NOT NULL,
    grade character varying(20) NOT NULL,
    recommended_resource text,
    total_score integer NOT NULL,
    interview_id bigint NOT NULL,
    CONSTRAINT interview_results_grade_check CHECK (((grade)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying, 'E'::character varying, 'F'::character varying])::text[])))
);


--
-- Name: interview_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interviewanswers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interviewanswers (
    answer_id integer NOT NULL,
    question_id integer NOT NULL,
    answer_text text NOT NULL,
    submitted_at timestamp without time zone NOT NULL
);


--
-- Name: interviewanswers_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.interviewanswers_answer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: interviewanswers_answer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.interviewanswers_answer_id_seq OWNED BY public.interviewanswers.answer_id;


--
-- Name: interviewquestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interviewquestions (
    question_id integer NOT NULL,
    text text NOT NULL,
    category character varying(50) NOT NULL,
    interview_id integer NOT NULL
);


--
-- Name: interviewquestions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.interviewquestions_question_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: interviewquestions_question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.interviewquestions_question_id_seq OWNED BY public.interviewquestions.question_id;


--
-- Name: interviewresults; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interviewresults (
    result_id integer NOT NULL,
    interview_id integer NOT NULL,
    total_score integer NOT NULL,
    grade character varying(20) NOT NULL,
    feedback text NOT NULL,
    recommended_resource text NOT NULL
);


--
-- Name: interviewresults_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.interviewresults_result_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: interviewresults_result_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.interviewresults_result_id_seq OWNED BY public.interviewresults.result_id;


--
-- Name: interviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interviews (
    interview_id bigint NOT NULL,
    user_id bigint NOT NULL,
    interview_type character varying(20) NOT NULL,
    job_position character varying(50) NOT NULL,
    career_level character varying(50) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    ended_at timestamp without time zone
);


--
-- Name: interviews_interview_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.interviews_interview_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: interviews_interview_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.interviews_interview_id_seq OWNED BY public.interviews.interview_id;


--
-- Name: likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.likes (
    user_id bigint NOT NULL,
    post_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: rankings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rankings (
    ranking_id integer NOT NULL,
    user_id integer NOT NULL,
    score integer NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT rankings_score_check CHECK (((score >= 0) AND (score <= 100)))
);


--
-- Name: rankings_ranking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rankings_ranking_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rankings_ranking_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rankings_ranking_id_seq OWNED BY public.rankings.ranking_id;


--
-- Name: scraps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scraps (
    scrap_id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);


--
-- Name: scraps_scrap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.scraps_scrap_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scraps_scrap_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.scraps_scrap_id_seq OWNED BY public.scraps.scrap_id;


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    profile_id bigint NOT NULL,
    career_level character varying(50),
    job character varying(50),
    profile_image_url character varying(500),
    user_id bigint NOT NULL
);


--
-- Name: user_profiles_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_profiles ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_rankings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_rankings (
    ranking_id bigint NOT NULL,
    average_score numeric(5,2) DEFAULT 0.0 NOT NULL,
    current_rank integer DEFAULT 0 NOT NULL,
    ranking_score numeric(7,2) DEFAULT 0.0 NOT NULL,
    total_interviews integer DEFAULT 0 NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: user_rankings_ranking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_rankings ALTER COLUMN ranking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_rankings_ranking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userprofiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.userprofiles (
    profile_id integer NOT NULL,
    user_id integer NOT NULL,
    job_position character varying(50),
    career_level character varying(20),
    profile_image text
);


--
-- Name: userprofiles_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.userprofiles_profile_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: userprofiles_profile_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.userprofiles_profile_id_seq OWNED BY public.userprofiles.profile_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    username character varying(20) NOT NULL,
    password character varying(250) NOT NULL,
    email character varying(100) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    provider character varying(100),
    provider_id character varying(100)
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: comments comment_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments ALTER COLUMN comment_id SET DEFAULT nextval('public.comments_comment_id_seq'::regclass);


--
-- Name: communityposts post_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.communityposts ALTER COLUMN post_id SET DEFAULT nextval('public.communityposts_post_id_seq'::regclass);


--
-- Name: interviewanswers answer_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewanswers ALTER COLUMN answer_id SET DEFAULT nextval('public.interviewanswers_answer_id_seq'::regclass);


--
-- Name: interviewquestions question_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewquestions ALTER COLUMN question_id SET DEFAULT nextval('public.interviewquestions_question_id_seq'::regclass);


--
-- Name: interviewresults result_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewresults ALTER COLUMN result_id SET DEFAULT nextval('public.interviewresults_result_id_seq'::regclass);


--
-- Name: interviews interview_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviews ALTER COLUMN interview_id SET DEFAULT nextval('public.interviews_interview_id_seq'::regclass);


--
-- Name: rankings ranking_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rankings ALTER COLUMN ranking_id SET DEFAULT nextval('public.rankings_ranking_id_seq'::regclass);


--
-- Name: scraps scrap_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scraps ALTER COLUMN scrap_id SET DEFAULT nextval('public.scraps_scrap_id_seq'::regclass);


--
-- Name: userprofiles profile_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.userprofiles ALTER COLUMN profile_id SET DEFAULT nextval('public.userprofiles_profile_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (comment_id);


--
-- Name: community_posts community_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_posts
    ADD CONSTRAINT community_posts_pkey PRIMARY KEY (id);


--
-- Name: communityposts communityposts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.communityposts
    ADD CONSTRAINT communityposts_pkey PRIMARY KEY (post_id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: interview_answers interview_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_answers
    ADD CONSTRAINT interview_answers_pkey PRIMARY KEY (answer_id);


--
-- Name: interview_questions interview_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_questions
    ADD CONSTRAINT interview_questions_pkey PRIMARY KEY (question_id);


--
-- Name: interview_results interview_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_results
    ADD CONSTRAINT interview_results_pkey PRIMARY KEY (result_id);


--
-- Name: interviewanswers interviewanswers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewanswers
    ADD CONSTRAINT interviewanswers_pkey PRIMARY KEY (answer_id);


--
-- Name: interviewquestions interviewquestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewquestions
    ADD CONSTRAINT interviewquestions_pkey PRIMARY KEY (question_id);


--
-- Name: interviewresults interviewresults_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewresults
    ADD CONSTRAINT interviewresults_pkey PRIMARY KEY (result_id, interview_id);


--
-- Name: interviews interviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviews
    ADD CONSTRAINT interviews_pkey PRIMARY KEY (interview_id);


--
-- Name: likes pk_likes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT pk_likes PRIMARY KEY (user_id, post_id);


--
-- Name: rankings rankings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rankings
    ADD CONSTRAINT rankings_pkey PRIMARY KEY (ranking_id);


--
-- Name: scraps scraps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scraps
    ADD CONSTRAINT scraps_pkey PRIMARY KEY (scrap_id);


--
-- Name: interview_answers uk2ydiuxvxwb5ddueavb1mm3my8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_answers
    ADD CONSTRAINT uk2ydiuxvxwb5ddueavb1mm3my8 UNIQUE (question_id);


--
-- Name: scraps uk_scraps_post_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scraps
    ADD CONSTRAINT uk_scraps_post_user UNIQUE (post_id, user_id);


--
-- Name: user_profiles uke5h89rk3ijvdmaiig4srogdc6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT uke5h89rk3ijvdmaiig4srogdc6 UNIQUE (user_id);


--
-- Name: user_rankings uknnxgkil29bnkwncymc5uiw63l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rankings
    ADD CONSTRAINT uknnxgkil29bnkwncymc5uiw63l UNIQUE (user_id);


--
-- Name: interview_results ukstsltuyb226ay5we7uxwh642k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_results
    ADD CONSTRAINT ukstsltuyb226ay5we7uxwh642k UNIQUE (interview_id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (profile_id);


--
-- Name: user_rankings user_rankings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rankings
    ADD CONSTRAINT user_rankings_pkey PRIMARY KEY (ranking_id);


--
-- Name: userprofiles userprofiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.userprofiles
    ADD CONSTRAINT userprofiles_pkey PRIMARY KEY (profile_id, user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_comments_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id);


--
-- Name: idx_comments_post_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_post_id_created_at ON public.comments USING btree (post_id, created_at DESC);


--
-- Name: idx_comments_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_user_id ON public.comments USING btree (user_id);


--
-- Name: idx_likes_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_likes_post_id ON public.likes USING btree (post_id);


--
-- Name: idx_likes_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_likes_user_id ON public.likes USING btree (user_id);


--
-- Name: idx_scraps_post_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scraps_post_id ON public.scraps USING btree (post_id);


--
-- Name: idx_scraps_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scraps_user_id ON public.scraps USING btree (user_id);


--
-- Name: user_rankings fk19peylp1bccve5myonqdka2ol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_rankings
    ADD CONSTRAINT fk19peylp1bccve5myonqdka2ol FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: interview_questions fk3dw8ec8nqxk4sv9gup5pk9sqs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_questions
    ADD CONSTRAINT fk3dw8ec8nqxk4sv9gup5pk9sqs FOREIGN KEY (interview_id) REFERENCES public.interviews(interview_id);


--
-- Name: community_posts fk44o0kkmkldhul00k2lm08bqje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_posts
    ADD CONSTRAINT fk44o0kkmkldhul00k2lm08bqje FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: interview_answers fk4kqx5jj1pfofmdtxoihtq2sg5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_answers
    ADD CONSTRAINT fk4kqx5jj1pfofmdtxoihtq2sg5 FOREIGN KEY (question_id) REFERENCES public.interview_questions(question_id);


--
-- Name: interviews fk5e4rxgf88qk96qk90lgngxrd0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviews
    ADD CONSTRAINT fk5e4rxgf88qk96qk90lgngxrd0 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: comments fk_comments_post; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES public.community_posts(id);


--
-- Name: comments fk_comments_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: communityposts fk_communityposts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.communityposts
    ADD CONSTRAINT fk_communityposts_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: interviewanswers fk_interviewanswers_question; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewanswers
    ADD CONSTRAINT fk_interviewanswers_question FOREIGN KEY (question_id) REFERENCES public.interviewquestions(question_id);


--
-- Name: interviewquestions fk_interviewquestions_interview; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewquestions
    ADD CONSTRAINT fk_interviewquestions_interview FOREIGN KEY (interview_id) REFERENCES public.interviews(interview_id);


--
-- Name: interviewresults fk_interviewresults_interview; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interviewresults
    ADD CONSTRAINT fk_interviewresults_interview FOREIGN KEY (interview_id) REFERENCES public.interviews(interview_id);


--
-- Name: likes fk_likes_post; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES public.community_posts(id) ON DELETE CASCADE;


--
-- Name: likes fk_likes_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: rankings fk_rankings_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rankings
    ADD CONSTRAINT fk_rankings_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: scraps fk_scraps_post; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scraps
    ADD CONSTRAINT fk_scraps_post FOREIGN KEY (post_id) REFERENCES public.community_posts(id) ON DELETE CASCADE;


--
-- Name: scraps fk_scraps_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scraps
    ADD CONSTRAINT fk_scraps_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: userprofiles fk_userprofiles_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.userprofiles
    ADD CONSTRAINT fk_userprofiles_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_profiles fkjcad5nfve11khsnpwj1mv8frj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT fkjcad5nfve11khsnpwj1mv8frj FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: interview_results fkq6qyo6qabe2389ygue60gf0gn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_results
    ADD CONSTRAINT fkq6qyo6qabe2389ygue60gf0gn FOREIGN KEY (interview_id) REFERENCES public.interviews(interview_id);


--
-- PostgreSQL database dump complete
--

